### PR TITLE
Change to condaforge/linux-anvil-cos7-x86_64 image and enable linux build

### PR DESCRIPTION
**Pull request by jonmmease**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jonmmease** [comment]
@conda-forge-admin, please rerender

**Comment by jonmmease** [comment]
@conda-forge-admin please rerender

**Comment by jonmmease** [comment]
@conda-forge-admin please rerender

**Comment by jonmmease** [comment]
@conda-forge-admin please rerender

**Comment by bandersen23** [comment]
@jonmmease Does this prevent CentOS 7 installs or am I misunderstanding that? I was receiving an Unsatisfiable error for `"__glibc >=2.17,<3.0.a0",` when trying to install the Linux version. I'm trying to understand why that is 👍 Thank you!

**Comment by jonmmease** [comment]
No, CentOS 7 should satisfy __glibc >=2.17 (https://centos.pkgs.org/7/centos-x86_64/glibc-2.17-317.el7.x86_64.rpm.html). 

Is this an x64 installation? FWIW, the ARM build isn't on conda-forge.

**Comment by bandersen23** [comment]
That was what I thought. I do have an x64 install. I'm suspicious that the feedstock replaced `sysroot_linux-64` with `__glibc` in the index.json. If you download the linux64 tar from [Anaconda](https://anaconda.org/conda-forge/kaleido-core/files) and look at the index.json file packaged up with it, you'll see that it will cause conda to look for `__glibc` rather than `sysroot linux-64`. [`sysroot_linux-64`](https://anaconda.org/conda-forge/sysroot_linux-64) resolves in conda, but [`__glibc`](https://anaconda.org/search?q=__glibc) will not (because it should be in the sysroot package referenced earlier).  Does that make sense to you? I'm at least thinking that is the problem. 

I hope you know that I don't think this PR is the root of the problem as it makes sense now that I've read it all, I just think something isn't resolving correctly. If this is the case, I'd assume there's a problem in how conda built the package, so it might be a simple fix to rebuild, but I'd defer to the conda-forge admin team if that's even possible 👍

**Pull request merged**
